### ISSUE TITLE
Automate Organization Invitations via @sanjay-kv

### ISSUE THREAD

**Issue by mdazfar2** [BrdigeWise-Tech/Support#1]
### 📋 Description
To streamline the process of inviting contributors to the BridgeWise-Tech GitHub organization, let's implement a GitHub Action workflow that automatically sends organization invitations. This workflow will make it easy for contributors to join by simply triggering an action, which will then send an invitation via **@sanjay-kv**.

### 💡 Suggested Workflow Outline
- Set up a GitHub Actions workflow file (e.g., `.github/workflows/invite.yml`).
- Define an event trigger, such as opening a new issue or a specific label (e.g., `invite-request`).
- Use GitHub Actions to send a notification to @sanjay-kv or directly send the invite.

> Let’s make it easy for people to become a part of the BridgeWise-Tech organization! 🚀

**Please review and share any feedback or suggestions for further improvement!**

**Comment by sanjay-kv** [comment]
This been done. :)
